# Generated by Django 2.1.15 on 2020-06-12 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_data',
            new_name='release_date',
        ),
        migrations.AlterField(
            model_name='movie',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
